# Generated by Django 3.2.9 on 2022-03-10 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='Unknown', max_length=50)),
                ('title', models.CharField(default='Unknown', max_length=50)),
                ('content', models.TextField(default='NO content')),
            ],
        ),
    ]
